config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]
  resources :reserves do
    resources :people
  end
  resources :boards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts

  root 'main_page#index'
  get 'main_page/program'
  get 'main_page/info'
  get 'main_page/road'
  get 'main_page/intro'
  get 'main_page/intro_house'
  get 'main_page/qna'
  get 'main_page/hwahye_type'
  get 'main_page/night_pro'
  get 'main_page/six_pro'
  get 'main_page/craft_pro'

end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
  has_many :people

  validates :title, :presence => true
  validates :content, :presence => true
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  before_action :set_reserf, only: [:show, :edit, :update, :destroy]

  # GET /reserves
  # GET /reserves.json
  def index
    @reserves = Reserve.all
  end

  # GET /reserves/1
  # GET /reserves/1.json
  def show
    @people = Person.all
  end

  # GET /reserves/new
  def new
    @reserf = Reserve.new
  end

  # GET /reserves/1/edit
  def edit
  end

  # POST /reserves
  # POST /reserves.json
  def create
    @reserf = Reserve.new(reserf_params)

    respond_to do |format|
      if @reserf.save
        format.html { redirect_to @reserf, notice: 'Reserve was successfully created.' }
        format.json { render :show, status: :created, location: @reserf }
      else
        format.html { render :new }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reserves/1
  # PATCH/PUT /reserves/1.json
  def update
    respond_to do |format|
      if @reserf.update(reserf_params)
        format.html { redirect_to @reserf, notice: 'Reserve was successfully updated.' }
        format.json { render :show, status: :ok, location: @reserf }
      else
        format.html { render :edit }
        format.json { render json: @reserf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reserves/1
  # DELETE /reserves/1.json
  def destroy
    @reserf.destroy
    respond_to do |format|
      format.html { redirect_to reserves_url, notice: 'Reserve was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def night_pro
    
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reserf
      @reserf = Reserve.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reserf_params
      params.require(:reserve).permit(:title, :content, :reser_time, :booking, :reser_type)
    end
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/views/reserves/_form.html.erb
<%= form_for(@reserf) do |f| %>
  <% if @reserf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reserf.errors.count, "error") %> prohibited this reserf from being saved:</h2>

      <ul>
      <% @reserf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :reser_time %><br>
    <%= f.date_select :reser_time %>
  </div>
  <div class="field">
    <%= f.label :people %><br>
    <%= f.number_field :booking %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reserves/edit.html.erb
<h1>Editing Reserf</h1>

<%= render 'form' %>

<%= link_to 'Show', @reserf %> |
<%= link_to 'Back', reserves_path %>

app/views/reserves/index.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>소개</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="pro_intro">
        <div class="form_content">
          <img src="/01_main/color_bar.png">
            <div class="t_head">
              <h2>프로그램명</h2>
              <h3>체험날짜</h3>
              <h4>가능인원</h4>
            </div>
            <hr>
            <div class="t_body">
              <% @reserves.each do |reserf| %>
                <% if reserf.booking == 0 %>
                  <p class="t_num"><%= reserf.title %></a></p>
                <% else %>
                  <p class="t_num"><a href="/reserves/<%= reserf.id %>/people/new"><%= reserf.title %></a></p>
                <% end %>
                <p class="t_date"><%= reserf.reser_time %></p>
                <p class="t_people"><%= reserf.booking %></p>
              <% end %>
            </div>
        </div>
        <img style="width: 90%; margin-bottom: 0" src="/01_main/color_bar.png">
      </div>
    </div>
  </div>
</div>

app/views/reserves/new.html.erb
<h1>New Reserf</h1>

<%= render 'form' %>

<%= link_to 'Back', reserves_path %>

app/views/reserves/show.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>소식</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="pro_intro">
        <p>
        <strong>Title:</strong>
        <%= @reserf.title %>
        </p>

        <p>
        <strong>Content:</strong>
        <%= @reserf.content %>
        </p>

        <p>
        <strong>Reser time:</strong>
        <%= @reserf.reser_time %>
        </p>

        <p>
        <strong>Booking:</strong>
        <%= @reserf.booking %>
        </p>

        <%= link_to 'Edit', edit_reserf_path(@reserf) %> |
        <%= link_to 'Back', reserves_path %>

        <% unless @reserf.booking == 0 %>
          <%= link_to '등록하기', new_reserf_person_path(@reserf) %>
        <% end %>
      </div>
    </div>
  </div>
</div>