config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]
  resources :reserves do
    resources :people
  end
  resources :boards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts

  root 'main_page#index'
  get 'main_page/program'
  get 'main_page/info'
  get 'main_page/road'
  get 'main_page/intro'
  get 'main_page/intro_house'
  get 'main_page/qna'
  get 'main_page/hwahye_type'
  get 'main_page/night_pro'
  get 'main_page/six_pro'
  get 'main_page/craft_pro'

end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :reserve
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    @reserf = Reserve.find(params[:reserf_id])
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @reserf = Reserve.find(params[:reserf_id])
  end

  # GET /people/new
  def new
    @person = Person.new
    @reserf = Reserve.find(params[:reserf_id])
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @reserf = Reserve.find(params[:reserf_id])
    @person = Person.new(person_params)
    @person.reserve_id=@reserf.id
    @reserf.booking-=@person.member
    @reserf.save

    respond_to do |format|
      if @person.save
        format.html { redirect_to [@reserf, @person], notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:reserve_id, :name, :phone1, :phone2, :member)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>소식</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <a href="/main_page/program"><li><p>프로그램</p></li></a>
        <a href="/reserves/index"><li><p>예약하기</p></li></a>
        <a href="/"><li><p>후기게시판</p></li></a>
      </div>
    </div>
    <div class="reserve_back">
      <div class="pro_intro">
        <%= form_for([@reserf, @person]) do |f| %>

          <div class="field">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="field">
            <%= f.label :phone1 %><br>
            <%= f.text_field :phone1 %>
          </div>
          <div class="field">
            <%= f.label :phone2 %><br>
            <%= f.text_field :phone2 %>
          </div>
          <% if @reserf.booking > 10 %>
            <input type="number" name="person[member]" min="1" max="10">
          <% else %>
            <input type="number" name="person[member]" min="1" max="<%= @reserf.booking %>">
          <% end %>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone1</th>
      <th>Phone2</th>
      <th>Member</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.phone1 %></td>
        <td><%= person.phone2 %></td>
        <td><%= person.member %></td>
        <td><%= link_to 'Show', reserf_person_path(@reserf, person) %></td>
        <td><%= link_to 'Edit', edit_reserf_person_path(@reserf, person) %></td>
        <td><%= link_to 'Destroy', reserf_person_path(@reserf, person), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_reserf_person_path %>

app/views/people/new.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>소식</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="reserve_intro">
        <div class="reser_head">
          <h1>체험 프로그램 예약하기</h1>
          <hr>
        </div>
        <div class="reserve_form">
          <%= form_for([@reserf, @person]) do |f| %>

            <div class="field">
              <img src="/program/check.png">
              <p>신청인 이름(단체명)</p>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <img src="/program/check.png">
              <p>주 연락처</p>
              <%= f.text_field :phone1 %>
            </div>
            <div class="field">
              <img src="/program/check.png">
              <p>보조 연락처</p>
              <%= f.text_field :phone2 %>
            </div>
            <div class="field">
              <img src="/program/check.png">
              <p>인원수</p>
              <% if @reserf.booking > 10 %>
                <input type="number" name="person[member]" min="1" max="10">
              <% else %>
                <input type="number" name="person[member]" min="1" max="<%= @reserf.booking %>">
              <% end %>
            </div>
            <div class="actions">
              <input type="submit" name="commit" value="등록하기">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/people/show.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>소개</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="pro_intro">
        <div class="show_content">
          <img src="/01_main/color_bar.png">
          <h2>예약이 완료되었습니다</h2>
          <div class="form_box">
            <a href="/reserves">
              <img src="/01_main/back.png">
            </a>
          </div>
        </div>
        <img style="width: 70%; margin-bottom: 0" src="/01_main/color_bar.png">
      </div>
    </div>
  </div>
</div>