config/routes.rb
Rails.application.routes.draw do
  devise_for :users, only: [:sessions]
  resources :reserves do
    resources :people
  end
  resources :boards
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts

  root 'main_page#index'
  get 'main_page/program'
  get 'main_page/info'
  get 'main_page/road'
  get 'main_page/intro'
  get 'main_page/intro_house'
  get 'main_page/qna'
  get 'main_page/hwahye_type'
  get 'main_page/night_pro'
  get 'main_page/six_pro'
  get 'main_page/craft_pro'

end

app/models/board.rb
class Board < ActiveRecord::Base
  validates :name, length: { maximum: 6 }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :title, :content)
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form' %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>소개</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="board_intro">
        <div class="board_content">
          <img src="/01_main/color_bar.png">
            <div class="t_head">
              <h2>NO</h2>
              <h3>글쓴이</h3>
              <h4>제목</h4>
              <!-- <h5>날짜</h5> -->
            </div>
            <hr>
            <div class="t_body">
              <% @boards.each do |board| %>
                <p class="t_num"><%= board.id %></p>
                <p class="t_name"><%= board.name %></p>
                <p class="t_title"><a href="/boards/<%= board.id %>"><%= board.title %></a></p>
                <!--<p class="t_date"><%# Time.zone.now.to_date %></p> -->
              <% end %>
            </div>

          <br>
        </div>
        <img src="/01_main/color_bar.png">
        <div class="list_img">
          <a href="/boards">
            <img src="/01_main/list.png">
          </a>
        </div>
        <div class="write_img">
          <a href="/boards/new">
            <img src="/01_main/write.png">
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/new.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>소개</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="form_intro">
        <div class="board_head">
          <h1> 후기 등록</h1>
          <hr>
        </div>
        <div class="board_form">
          <%= form_for(@board) do |f| %>
            <div class="field">
              <p>작성자 이름</p>
              <%= f.text_field :name %>
            </div>
            <div class="field">
              <p>제목</p>
              <%= f.text_field :title %>
            </div>
            <div class="field">
              <%= f.text_area :content %>
            </div>
            <div class="actions">
              <button type="submit">
                <img src="/01_main/write.png">
              </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="main">
  <div class="menu_logo">
    <div class="hori_logo">
      <a href="/">
        <img src="/01_main/main_logo.png" class="logo">
        <img src="/program/hori_logo.png" class="logo_name">
      </a>
    </div>
    <div class="menu_bar">
      <a href="/main_page/intro">
        <div class="menu_hwahye area">
          <p>소개</p>
        </div>
      </a>
      <a href="/main_page/info">
        <div class="menu_info area">
          <p>화혜</p>
        </div>
      </a>
      <a href="/main_page/program">
        <div class="menu_program area">
          <p>프로그램</p>
        </div>
      </a>
      <a href="/main_page/road">
        <div class="menu_road area">
          <p>오시는길</p>
        </div>
      </a>
      <a href="/main_page/qna">
        <div class="menu_qna area">
          <p>문의하기</p>
        </div>
      </a>
    </div>
  </div>
  <div class="pro_content color_back">
    <div class="left_side">
      <div class="sub_menu">
        <div class="sub_bar">
          <a href="/main_page/program"><li><p>프로그램</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/reserves"><li><p>예약하기</p></li></a>
        </div>
        <div class="sub_bar">
          <a href="/boards"><li><p>후기게시판</p></li></a>
        </div>
      </div>
    </div>
    <div class="reserve_back">
      <div class="board_intro">
        <div class="board_content">
            <img src="/01_main/color_bar.png">

            <div class="board_row">
              <p class="t_title">제목 : <%= @board.title %></a></p>
              <p class="t_name">작성자 : <%= @board.name %></p>
            </div>
            <div class="board_main">
              <p class="t_content"><%= @board.content %></a></p>
            </div>

        </div>
        <img src="/01_main/color_bar.png">
        <div class="list_img">
          <a href="/boards">
            <img src="/01_main/list.png">
          </a>
        </div>
      </div>
    </div>
  </div>
</div>